const REPORT_CATEGORIES = {
  FIRE: 'incendio',
  FLOOD: 'inundacion',
  CRIME: 'delito',
  ACCIDENT: 'accidente',
  ROAD_BLOCK: 'bloqueo',
  INFRASTRUCTURE: 'infraestructura',
  OTHER: 'otros',
};

const REPORT_CATEGORY_LABELS = {
  [REPORT_CATEGORIES.FIRE]: 'Incendio',
  [REPORT_CATEGORIES.FLOOD]: 'Inundación',
  [REPORT_CATEGORIES.CRIME]: 'Delito',
  [REPORT_CATEGORIES.ACCIDENT]: 'Accidente',
  [REPORT_CATEGORIES.ROAD_BLOCK]: 'Bloqueo vial',
  [REPORT_CATEGORIES.INFRASTRUCTURE]: 'Infraestructura urbana',
  [REPORT_CATEGORIES.OTHER]: 'Otros',
};

const REPORT_PRIORITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
};

const CATEGORY_DEFAULT_PRIORITY = {
  [REPORT_CATEGORIES.FIRE]: REPORT_PRIORITY.CRITICAL,
  [REPORT_CATEGORIES.FLOOD]: REPORT_PRIORITY.HIGH,
  [REPORT_CATEGORIES.CRIME]: REPORT_PRIORITY.HIGH,
  [REPORT_CATEGORIES.ACCIDENT]: REPORT_PRIORITY.HIGH,
  [REPORT_CATEGORIES.ROAD_BLOCK]: REPORT_PRIORITY.MEDIUM,
  [REPORT_CATEGORIES.INFRASTRUCTURE]: REPORT_PRIORITY.LOW,
  [REPORT_CATEGORIES.OTHER]: REPORT_PRIORITY.LOW,
};

const REPORT_CATEGORY_LIST = Object.values(REPORT_CATEGORIES);

module.exports = {
  REPORT_CATEGORIES,
  REPORT_CATEGORY_LABELS,
  REPORT_CATEGORY_LIST,
  REPORT_PRIORITY,
  CATEGORY_DEFAULT_PRIORITY,
};
